### ISSUE TITLE
`Error: No module named 'packaging'`Get python package from Pypi not work

### ISSUE THREAD

**Issue by xiongchenyu6** [berberman/nvfetcher#118]
❯ cat nvfetcher.toml
# nvfetcher.toml
[feeluown]
src.pypi = "feeluown"
fetch.pypi = "feeluown"%                                                                                                                                                                            
❯ nvfetcher
# CheckPypi: feeluown
Error: No module named 'packaging'
Error: No module named 'packaging'
Error: No module named 'packaging'
nvfetcher: Error when running Shake build system:
  at want, called at src/NvFetcher.hs:167:25 in nvfetcher-0.6.2.0-2oqz5Z2t3Fp6rVQQnP9T9a:NvFetcher
* Depends on: build
  at apply1, called at src/NvFetcher/Core.hs:126:16 in nvfetcher-0.6.2.0-2oqz5Z2t3Fp6rVQQnP9T9a:NvFetcher.Core
* Depends on: Core ("feeluown")
  at apply1, called at src/NvFetcher/Nvchecker.hs:207:22 in nvfetcher-0.6.2.0-2oqz5Z2t3Fp6rVQQnP9T9a:NvFetcher.Nvchecker
* Depends on: CheckVersion (Pypi {_pypi = "feeluown"}) (NvcheckerOptions {_stripPrefix = Nothing, _fromPattern = Nothing, _toPattern = Nothing}) ("feeluown")
  at cmd, called at src/NvFetcher/Nvchecker.hs:110:51 in nvfetcher-0.6.2.0-2oqz5Z2t3Fp6rVQQnP9T9a:NvFetcher.Nvchecker
* Raised the exception:
Development.Shake.cmd, system command failed
Command line: nvchecker --logger json -c /tmp/extra-file-96487289080586-153575-0
Exit code: 1
Stderr:
Error: No module named 'packaging'

**Comment by xiongchenyu6** [comment]
> Your nvchecker didn't seem to work properly. How did you install it?

Just nix run github:berberman/nvfetcher, and my system is unstable version of nixos
![image](https://github.com/berberman/nvfetcher/assets/4978864/737880c8-25dd-431f-80d9-b715462601be)

**Comment by berberman** [comment]
Dependency `packaging` is missing in nvchecker 2.13.1. Should be fixed by https://github.com/NixOS/nixpkgs/pull/297257
