### ISSUE TITLE
Feature request???

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [berberman/nvfetcher#3]
Hey, a little while back I was thinking of building something similar to this project but it is missing multiple features. And I was wondering if it's part of the roadmap.

Here is the features list:
- Following branch/tag depending on regex (Example: Updating package to latest GCC 10.x version according to the tags)
- Post processing (Some way to perform impure operations to calculate stuff like cargoSha256)

I realize, these are not minor tweaks, but I am just interested in the overall future of this project - maybe you could comment on this?

**Comment by blaggacao** [comment]
@berberman & @gytis-ivaskevicius I would really welcome both of you collaborating on those ideas. I think `nvfetcher` has real potential since it strictly honors the fundamentals of [standing on the shoulders of giants](https://en.wikipedia.org/wiki/Standing_on_the_shoulders_of_giants) by relying on `nvchecker`, which has a pretty comprehensive upstream source support.

**Comment by gytis-ivaskevicius** [comment]
Oh no!! I am being encouraged to learn Haskell :pleading_face: 
Maybe, maybe I'm up for the job. Tho first I'd like to hear what @berberman has to say about the goals of this project

**Comment by berberman** [comment]
Hi, thanks for the feature request.

> Following branch/tag depending on regex (Example: Updating package to latest GCC 10.x version according to the tags)

This is an existing feature of `nvchecker`, so it's very easy to implement it for us, which I've just done in 9891d0d:
https://github.com/berberman/nvfetcher/blob/9891d0d6322873e70a2060d36d13a3144508ced9/nvfetcher_example.toml#L25-L29

> Post processing (Some way to perform impure operations to calculate stuff like cargoSha256)

I'm not against adding language specific things, but afaik handling this for Rust or Go is tricky, which other related projects might have been facing the similar problem. Unfortunately, I know little about  tooling in nix for languages other than Haskell... However, it might not be so difficult, as the internal structure of `nvfetcher` is very extensible, which let us add components easily. So the key questions here is what do we need to calculate `cargoSha256`. But notice that https://github.com/NixOS/nixpkgs/pull/122158 was merged recently - do we need `cargoSha256` anymore? Perhaps I need some help from nix + rust experts. 

> I realize, these are not minor tweaks, but I am just interested in the overall future of this project - maybe you could comment on this?

To be honest, there is no futre plan at all. I'm happy to see this project could be used by more people, and there will be more contributors.

**Comment by gytis-ivaskevicius** [comment]
Alright, that's cool.
I guess ill start learning Haskell and probably next weekend will give a shot with this codebase. Thinking about adding `meta` entries autogeneration from github/gitlab. That should be easy enough :)
