### ISSUE TITLE
Feature request: Add docker image support

### ISSUE THREAD

**Issue by TLATER** [berberman/nvfetcher#33]
There is [support for pulling docker images in nixpkgs](https://nixos.org/manual/nixpkgs/stable/#ssec-pkgs-dockerTools-fetchFromRegistry), and it would be awesome to use nvfetcher to update the digest/sha for this.

[nvchecker](https://nvchecker.readthedocs.io/en/latest/usage.html#check-container-registry) also has support for checking docker registries.

It seems like most of the pieces are in place, it just needs some wiring for nvfetcher to create sources. I've tried patching this together myself, but I'll probably need a crash course on haskell before I can actually do this, so I'll leave this issue here for now :)

**Comment by amesgen** [comment]
I would also be interested in this, might take a stab at it in the near future.

One small design point would be that nvchecker only supports fetching tags, which are technically mutable (see https://discourse.nixos.org/t/how-to-update-a-declarative-docker-container/8679/3), but I have no idea how often that actually happens. But I think that tags would already be useful, even without digests.

**Comment by TLATER** [comment]
Shout if you want review or something of the sort - I've since learned haskell, but stopped using docker images ;)

**Comment by amesgen** [comment]
@TLATER Feel free to have a look at #33 if you want, but don't feel pressured in any way :smile:

**Comment by TLATER** [comment]
I see the actual maintainer just got around to it instead :) Thanks for the feature!
