### ISSUE TITLE
Post processors support

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [berberman/nvfetcher#4]
It would be cool to add a few post processors for impure operations and for "nice to have" information. This is just a proper issue in response to https://github.com/berberman/nvfetcher/issues/3

Postprocessors that I already have in mind: (Feel free to add other ideas in the comments below)
- Derivation `meta` attributes generation
- Integration with Rust/Golang dependencies (Rust might be resolved, need to play around with it https://github.com/NixOS/nixpkgs/pull/122158)
- Meson options parsing

**Comment by berberman** [comment]
The post process of `cargoSha256` is work in prograss, which is considered to be a legacy though. What will "Meson options parsing" be like? Could you elaborate it?

**Comment by gytis-ivaskevicius** [comment]
Yeah, for rust there is not much else that can be done. From what I saw in PR above - it might be nice to autogenerate `outputHashes` - this way you would not need to touch dependencies manually but it already seems great :)

As for `meta` - The whole idea of mines is to autogenerate as much of derivation definition as possible. This would allow keeping the homepage/description/licensing in sync and overall forget about these kind of copy/paste options.

meson options are basically compile-time feature flags. Here is a massive example https://github.com/systemd/systemd/blob/main/meson_options.txt
Currently, nixpkgs derivations specify these flags as strings, use cases that would be nice to have:
- Straight up type validation
- Visibility - when updating the derivation its options would update as well and would provide extra visibility. This would encourage users to tweak their derivations to account for certain changes (Add a feature flag or disable something that is unnecessary or fix up some certain path)
- In the case of something like systemd one could easily loop over all options and enable only a select few features. This would simplify building of only a select few components of systemd. (For example, tmpfiles are great, it might as well be converted to derivation builder or used partially by home-manager)

**Comment by gytis-ivaskevicius** [comment]
Would "post processor" in the shape of an executable that returns some JSON would be fine?
I'd imagine something along the lines of specifying a script path in toml file.

This way any kind of post-processor could be implemented without touching this repo

**Comment by berberman** [comment]
I see, thank you for your detailed explanation. But unfortunately, I think this kind of post-process is **totally** beyond the scope of this project: please keep in mind that the project name is `nvfetcher`, which is designed to automatically tracking and updating *sources* of packages, rahter than to convert arbitrary projects to nix. So I'm going to close this issue.

**Comment by berberman** [comment]
Now `nvfetcher` supports extract arbitrary text file from fetched source to generated nix expr, for example:

Given the following configuration,

```toml
[fd]
src.github = "sharkdp/fd"
fetch.github = "sharkdp/fd"
extract = ["Cargo.lock"]
```

`nvchecker` produces `sources.nix` which includes the contents of `Cargo.lock`

```nix
# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  fd = {
    pname = "fd";
    version = "v8.2.1";
    src = fetchgit {
      url = "https://github.com/sharkdp/fd";
      rev = "v8.2.1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "00vlifbri021z8nf7xvbaay8mqvnq58h19va9bqr5lhsqj1f82wq";
    };
    "Cargo.lock" = ''
    # This file is automatically @generated by Cargo.
    # It is not intended for manual editing.
    [[package]]
    name = "aho-corasick"
    version = "0.7.15"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "7404febffaa47dac81aa44dba71523c9d069b1bdc50a77db41195149e17f68e5"
    dependencies = [
     "memchr",
    ]
    # ...
    '';
  };
}
```

so you can do any post-process after running `nvchecker`.

**Comment by blaggacao** [comment]
@berberman that's a _very_ elegant offering! Thank you!
