### ISSUE TITLE
Feature request: use fetched hash

### ISSUE THREAD

**Issue by danielphan2003** [berberman/nvfetcher#42]
[Modrinth][modrinth] has a file API that also includes file hashes like sha512 or sha1. I guess we can use the hash for generating nix expr. Is this a good feature to add or should nix-prefetch-url check for the hash instead?

Try: `curl https://api.modrinth.com/api/v1/mod/kKwy3HU9/version | jq -r 'map(.files[])'`

[modrinth]: https://modrinth.com

**Comment by berberman** [comment]
nvfetcher calls nvchecker and then uses nix-prefetch to get hashes. If you already have file hashes, I think there's no need to use nvfetcher. Instead, you can write a simple program that interpolates your hashes.

**Comment by danielphan2003** [comment]
Make sense, I'll probably close this later.
