### ISSUE TITLE
optimize shake db size

### ISSUE THREAD

**Issue by danielphan2003** [berberman/nvfetcher#47]
With https://github.com/danielphan2003/nixpkgs/blob/main/pkgs/misc/vscode-extensions/open-vsx.toml, my shake db is around 100mb. I have no idea why it grew in size so much, maybe shake db includes all the passthru attrs?

![2022-01-09_23-01-19](https://user-images.githubusercontent.com/34669737/148692359-79cc3f43-d070-4b71-9461-5d43bfcf09e9.png)

**Comment by berberman** [comment]
Yes, actually generated nix expression for each package is cached, which includes passthru attrs. This is not good. Can you try #48 to see if the db size reduces?

**Comment by danielphan2003** [comment]
Of course. Here is the size after trying out #48:

![2022-01-10_08-01-20](https://user-images.githubusercontent.com/34669737/148710112-d037c782-62cf-43a7-94b4-0d8d9830a47e.png)

Db size reduced by 73%! I'm glad I don't make git complains anymore. I suppose this can be improved further, but maybe at a cost of slower package fetching time. What else does the db track besides package versions that accounts for the rest 27mb?

**Comment by berberman** [comment]
I run nvfetcher (on #48) with packages about half of your `open-vsx.toml`, but the database was only 1.4 MiB. In your case, generally the database includes:

* all keys of rules as shown in console output (e.g. for package "SonarSource-sonarlint-vscode", they are `CheckVersion (Manual {_manual = "3.1.0"}) (NvcheckerOptions {...}) ("SonarSource-sonarlint-vscode")`, `OracleQ (FetchUrl {_furl = "https://open-vsx.org/api/SonarSource/sonarlint-vscode/3.1.0/file/SonarSource.sonarlint-vscode-3.1.0.vsix", _name = Nothing, _sha256 = ()})`, `OracleQ Core ("SonarSource-sonarlint-vscode")`)
* the result of rule `CheckVersion` (current version and last time version)
* the result of rule `FetchUrl` (sha256 sum)
* shake internal states

Those things are accumulative over **each run**.  That said saved out-dated keys and results will never be invalidated. I'm not sure how the database can grow to 27MiB. Maybe you can try `nvfetcher clean` and rerun again.

**Comment by danielphan2003** [comment]
I suppose during CI the db can get cluttered. When there's a package rename, removal, or new package, the db can get invalidated (

**Comment by danielphan2003** [comment]
`nvfetcher clean` did the job https://github.com/danielphan2003/nixpkgs/blob/92f581bcb21c810fdde48a019078d4b97356e519/pkgs/_sources/open-vsx/.shake.database

**Comment by berberman** [comment]
Could you please try #49 on your packages one more time?

**Comment by danielphan2003** [comment]
With #48:

![2022-01-11_08-01-11](https://user-images.githubusercontent.com/34669737/148892090-4d66a29b-9afb-46b7-80aa-41fd1cbc5ae7.png)

With #49:

![2022-01-11_13-01-17](https://user-images.githubusercontent.com/34669737/148892127-7057fde1-cdb5-4efc-9eb5-f912e2450b2e.png)

Huh, I guess I have to let my CI test this instead. My internet connection isn't that fast :/

**Comment by berberman** [comment]
Thanks for confirming. Looks reasonable except the open-vsx one. Anyway, the size is acceptable now, right?

**Comment by danielphan2003** [comment]
Yep, go ahead and merge #49 :)
