### ISSUE TITLE
Civilize runtime output

### ISSUE THREAD

**Issue by berberman** [berberman/nvfetcher#56]
As suggested by @NickCao, the current output of nvchecker like:
```
# nvchecker (for CheckVersion (GitHubTag {_owner = "gcc-mirror", _repo = "gcc", _listOptions = ListOptions {_includeRegex = Just "releases/gcc-10.*", _excludeRegex = Nothing, _sortVersionKey = Nothing, _ignored = Nothing}}) (NvcheckerOptions {_stripPrefix = Nothing, _fromPattern = Nothing, _toPattern = Nothing}) ("gcc-10"))
```
is hard for human to read. Actually it is `show` (or `toString()` in Java) of Haskell data types. We need figure out a better form of the output.

**Comment by NickCao** [comment]
Some possible ideas:
- structured log (like json), to be more machine readable
- just print generated nvchecker config and nix-prefetch command, to make the underlying operations be more transparent
- print only important fields in a human friendly format
